config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

  post '/compra/:slug', to: 'transactions#create', as: :compra
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

  get 'dashboard' => 'pages#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord

    extend FriendlyId
    friendly_id :titolo, use: :slugged

    belongs_to :user, :optional => true

    has_many :sales

    has_attached_file :cover, styles: { medium: "300x>", thumb: "100x>" }
    validates_attachment_content_type :cover, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"],
    message: "Solo le immagini sono supportate"

    has_attached_file :allegato
    validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ],
    message: "Formato non supportato"

    validates :titolo, :descrizione, :prezzo, presence: true
    validates :prezzo, numericality: { greater_than: 0.49 }
    validates :cover, attachment_presence: true
    validates :allegato, attachment_presence: true

end

app/models/sale.rb
class Sale < ApplicationRecord

  before_create :generate_guid
  belongs_to :content

  include AASM

  aasm column: 'state' do
    state :sleeping, :initial => true
    state :running
    state :completed
    state :errored

      event :running, after: :charge_card do
        transitions from: :sleeping, to: :running
      end

      event :complete do
        transitions from: :running, to: :completed
      end

      event :fail do
        transitions from: :running, to: :errored
      end

  end

  def charge_card
    begin
      save!
      charge = Stripe::Charge.create(
        amount: self.amount,
        currency: "eur",
        card: self.stripe_token,
        description: "vendita di un contenuto")
      self.update(stripe_id: charge.id)
      self.complete!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!
    end
  end

  private

    def generate_guid
      self.guid = SecureRandom.uuid()
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contents

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      store_location_for(:user, request.fullpath)
    end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]
  def index
    @contents = Content.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
  end


  def show
  end


  def new
    @content = current_user.contents.build
  end


  def edit
  end


  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Contenuto creato con successo.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Contenuto aggiornato con successo.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Contenuto cancellato con successo.' }
    end
  end

  private

    def set_content
      @content = Content.friendly.find(params[:id])
    end


    def content_params
      params.require(:content).permit(:titolo, :descrizione, :prezzo, :cover, :allegato)
    end

    def check_user
      if current_user != @content.user
        redirect_to root_url, alert:"Scusa ma non hai l'autorizzazione a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def home
  end

  def about
  end

  def dashboard
    @content = current_user.contents
    @sales = Sale.where(email_venditore: current_user.email)
    @purchased = Sale.where(email_acquirente: current_user.email)
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def create
    content = Content.find_by!(slug: params[:slug])
    sale = content.sales.create(
      amount: (content.prezzo * 100).floor,
      email_acquirente: current_user.email,
      email_venditore: content.user.email,
      stripe_token: params[:stripeToken])
    sale.running!
    if sale.completed?
      redirect_to pickup_url(guid: sale.guid)
    else
      redirect_to content_path(content), notice: @error
    end

    end

  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @content = @sale.content
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true, html: { multipart: true } ) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h4><b><%= pluralize(content.errors.count, "error") %> non permettono al form di essere inviato</b></h4>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="grey-text">Carica il contenuto digitale che vuoi vendere</label>
    <br>
    <%= form.file_field :allegato, id: :content_allegato %>
  </div>
  <br>
  <div class="field">
    <%= form.label :titolo %>
    <%= form.text_field :titolo, id: :content_titolo %>
  </div>

  <div class="field">
    <%= form.label :descrizione %>
    <%= form.text_area :descrizione, id: :content_descrizione, class: "materialize-textarea" %>
  </div>

  <div class="field">
    <%= form.label :prezzo_min_50_cent %>
    <%= form.text_field :prezzo, id: :content_prezzo %>
  </div>

  <div class="field">
    <label class="grey-text">Carica l'immagine</label>
    <br>
    <%= form.file_field :cover, id: :content_cover %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Salva Contenuto', class: "btn btn-form" %>
  </div>
  <br>
<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modifica Contenuto <%= @content.titolo %></h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra', @content %> |
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/index.html.erb
<div class="row">
    <% @contents.each do |content| %>
      <div class="col s6 m4 l4">
        <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <%= image_tag content.cover.url, class: "activator" %>
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4"><%= content.titolo %>
                <i class="material-icons right">more_vert</i></span>
              <div>
                  <span>Venduto da <%= content.user.name %></span>
                  <span class="right"><%= number_to_currency(content.prezzo) %></span>
              </div>
              <br>
                <div class="center">
                  <%= link_to 'Scopri di più', content, class: "btn" %>
                </div>
                <% if content.user == current_user %>
                <br>
                <div class="center">
                  <p><%= link_to 'Modifica', edit_content_path(content) %>
                  <%= link_to 'Cancella', content, method: :delete, data: { confirm: 'Sei sicuro di voler cancellare?' } %></p>
                </div>
                <% end %>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><%= content.titolo %>
                <i class="material-icons right">chiudi</i></span>
              <p><%= content.descrizione %></p>
            </div>
        </div>
    </div>
    <% end %>
  </div>

<br>

<div class="center">
<%= will_paginate @contents, renderer: MaterializePagination::Rails %>
</div>

app/views/contents/new.html.erb
<h1 class="center">Aggiungi Contenuto</h1>

<%= render 'form', content: @content %>

<%= link_to 'Trona ai contenuti', contents_path %>

app/views/contents/show.html.erb
<div class="content-show">
  <div class="row">
    <div class="col l6">
      <%= image_tag @content.cover.url, class: "responsive-img show_img" %>
    </div>
    <div class="col l6">
      <h1 class="show_titolo">Titolo: <strong><%= @content.titolo %></strong></h1>
      <h4 class="show_prezzo">Prezzo: <strong><%= number_to_currency(@content.prezzo) %></strong></h4>
      <p>Venduto da <strong><%= @content.user.name %></strong></p>
      <p>Descrizione: <strong><%= @content.descrizione %></strong></p>

      <% if current_user %>
          <%= form_tag compra_path(slug: @content.slug) do %>
            <script
              src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-amount="<%= (@content.prezzo* 100).floor %>"
              data-name="EffeDiMarket"
              data-description="<%= @content.titolo %>"
              data-email="<%= current_user.email %>"
              data-currency="eur"
              data-locale="auto">
            </script>
            <% end %>

      <% else %>
        <p>Fai il <%= link_to "Log In", new_user_session_path %> o
        <%= link_to "Registrati", new_user_registration_path %> per acquistare</p>
      <% end %>
    </div>
  </div>
</div>

<% if @content.user == current_user %>
<%= link_to 'Modifica', edit_content_path(@content) %> |
<% end %>
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer blue darken-4 center">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s4">
          © 2018 EffeDiWeb
        </div>
        <div class="col s4">
          <a href="" target="_blank"><i class="fab fa-facebook-f fa-2x white-text"></i></a>
          <a href="" target="_blank"><i class="fab fa-twitter fa-2x white-text"></i></a>
          <a href="" target="_blank"><i class="fab fa-instagram fa-2x white-text"></i></a>
        </div>
        <div class="col s4">
          <%= link_to "About", about_path, class:"grey-text text-lighten-4 right" %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<div class="navbar-fixed">
  <nav class="blue darken-4">
      <div class="container nav-wrapper">
        <%= link_to "EffeDiMarket", root_path, class:"brand-logo" %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Inserisci Contenuto', new_content_path %></li>
          <% if user_signed_in? %>
          <ul id="dropdown1" class="dropdown-content">
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Impostazioni", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
          <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Registrazione", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
</div>
  <ul class="side-nav" id="mobile-demo">
    <li><%= link_to 'Inserisci Contenuto', new_content_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Impostazioni", edit_user_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Log In", new_user_session_path %></li>
    <li><%= link_to "Registrazione", new_user_registration_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EffeDiMarket</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,600" rel="stylesheet">
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</head>

<body>

<%= render "layouts/header" %>
<div class="container">
  <%= flash.each do |type, message| %>
    <script>
    Materialize.toast('<%= message %>', 4000);
    </script>
  <% end %>
</div>

<%= render "pages/slider" if action_name == "home" %>

<main class="container">
  <%= yield %>
</main>
<%= render "layouts/footer" %>

</body>

  <script>
  $(".button-collapse").sideNav();
  </script>

  <script>
  $('.carousel.carousel-slider').carousel({fullWidth: true});
  </script>

  <script>
  $(document).ready(function(){
    $('ul.tabs').tabs();
  });
  </script>

  <script>
  $(document).ready(function(){
        $('.parallax').parallax();
      });
  </script>

  <script>
  $(document).ready(function(){
  $(".dropdown-button").dropdown();
  });
  </script>

</html>

app/views/pages/_slider.html.erb
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <br><br>
      <div class="row center">
        <h1>EffeDiMarket</h1>
        <h5>A modern
          responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <%= link_to "Vai ai contenuti", contents_path, class:"btn red btn-large"%>
      </div>
      <br><br>
    </div>
    <div class="parallax"><%= image_tag("01.jpg") %></div>
  </div>

app/views/pages/about.html.erb

<h1>CHI SIAMO</h1>

app/views/pages/dashboard.html.erb
<h1 class="center">Dashboard</h1>

<div class="row">
   <div class="col s12">
     <ul class="tabs">
       <li class="tab col s3"><a href="#storico">Storico</a></li>
       <li class="tab col s3"><a href="#vendita">In vendita</a></li>
     </ul>
   </div>
   <div id="storico" class="col s12">
    <h4><b>Venduti</b></h4>
     <table>
       <thead>
         <tr>
           <th>Nome</th>
           <th>Prezzo</th>
           <th>Data di creazione</th>
           <th>Acquirente</th>
         </tr>
       </thead>
       <tbody>
           <% @sales.each do |sale| %>
           <tr>
             <th><%= link_to sale.content.titolo %></th>
             <th><%= number_to_currency(sale.amount / 100) %></th>
             <th><%= time_ago_in_words(sale.created_at) %> fa</th>
             <th><%= sale.email_acquirente %></th>
           </tr>
           <% end %>
        </tbody>
     </table>
     <br><br>
     <h4><b>Acquisti</b></h4>
     <table>
       <thead>
         <tr>
           <th>Nome</th>
           <th>Prezzo</th>
           <th>Data di creazione</th>
           <th>Venditore</th>
         </tr>
       </thead>
       <tbody>
           <% @purchased.each do |purchased| %>
           <tr>
             <th><%= link_to purchased.content.titolo, pickup_path(purchased.guid) %></th>
             <th><%= number_to_currency(purchased.amount / 100) %></th>
             <th><%= time_ago_in_words(purchased.created_at) %> fa</th>
             <th><%= purchased.email_venditore %></th>
           </tr>
           <% end %>
        </tbody>
     </table>
   </div>
   <div id="vendita" class="col s12">
     <table>
       <thead>
         <tr>
           <th>Nome</th>
           <th>Prezzo</th>
           <th>Data di creazione</th>
           <th>Azione</th>
         </tr>
       </thead>
       <tbody>
           <% @content.each do |content| %>
           <tr>
             <th><%= link_to content.titolo, content_path(content) %></th>
             <th><%= number_to_currency(content.prezzo) %></th>
             <th><%= time_ago_in_words(content.created_at) %> fa</th>
             <th><%= link_to "Modifica", edit_content_path(content) %>
              | <%= link_to "Elimina", content, method: :delete, data: { confirm: 'Sei sicuro di voler eliminare il contenuto?'} %>
            </th>
           </tr>
           <% end %>
        </tbody>
     </table>
   </div>
 </div>

app/views/pages/home.html.erb
<div class="center">
    <div class="row">
      <h2 class="sottotitolo">Il nostro negozio</h2>
      <div class="col s12 m4">
          <i class="material-icons medium blue-grey-text text-darken-3">library_books</i>
          <h5>Scopri contenuti unici</h5>
          <p>We did most of the heavy liftin
            g for you to provide a default stylings that in
            corporate our custom components. Additionally, w
            e refined animations and transitions to provide
            a smoother experience for developers.</p>
      </div>

      <div class="col s12 m4">
          <i class="material-icons medium blue-grey-text text-darken-3">motorcycle</i>
          <h5>Acquista velocemente</h5>
          <p>By utilizing elements and prin
            ciples of Material Design, we were able to cre
            ate a framework that incorporates components an
            d animations that provide more feedback to users.
            Additionally, a single underlying responsive system
             across all platforms allow for a more unified user experience.</p>
      </div>

      <div class="col s12 m4">
          <i class="material-icons medium blue-grey-text text-darken-3">library_add</i>
          <h5>Vendi i tuoi contenuti</h5>
          <p>We have provided detailed documentati
            on as well as specific code examples to help new u
            sers get started. We are also always open t
            o feedback and can answer any questions a use
            r may have about Materialize.</p>
        </div>

    </div>
</div>

app/views/transactions/pickup.html.erb
<h1>Grazie per aver acquistato <%= @content.titolo %></h1>

<p><%= link_to"Scarica qui", @content.allegato.url %> il tuo contenuto</p>